import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        primary: '#9e4300',
        'primary-container': '#f2711c',
        'on-primary': '#ffffff',
        'on-primary-container': '#532000',
        'on-primary-fixed': '#341100',
        'primary-fixed': '#ffdbcf',
        'inverse-primary': '#ffb691',
        secondary: '#77574a',
        'secondary-container': '#e4e2e1',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#656464',
        tertiary: '#006398',
        'tertiary-container': '#cce5ff',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#001e31',
        'on-tertiary-fixed-variant': '#004b74',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#410002',
        surface: '#fbf9f8',
        'surface-variant': '#f5ddd6',
        'surface-container': '#f0eded',
        'surface-container-low': '#f6f3f2',
        'surface-container-high': '#eae8e7',
        'surface-container-highest': '#e4e2e1',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#584237',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f3f0ef',
        outline: '#867067',
        'outline-variant': '#dfc0b2',
        background: '#fbf9f8',
        'on-background': '#1b1c1c',
      },
      fontFamily: {
        headline: ['Epilogue', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        sans: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        none: '0',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.375rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      boxShadow: {
        tectonic: '0 24px 40px -10px rgba(27, 28, 28, 0.06)',
        'tectonic-sm': '0 12px 24px -6px rgba(27, 28, 28, 0.06)',
        'tectonic-hover': '0 32px 48px -10px rgba(27, 28, 28, 0.10)',
        tonal: '0 1px 3px rgba(158,67,0,0.12), 0 1px 2px rgba(158,67,0,0.08)',
        'tonal-hover': '0 4px 8px rgba(158,67,0,0.16), 0 2px 4px rgba(158,67,0,0.12)',
      },
    },
  },
  plugins: [],
}

export default config
